### ISSUE TITLE
Missing fields  in cf:logmessage

### ISSUE THREAD

**Issue by sabarivijayan-fd** [cloudfoundry-community/splunk-firehose-nozzle#169] opened 2019-04-25 10:51 UTC
Hi,

we experience missing fields in sourcetype cf:logmessage sent by splunk-firehose-nozzle to our splunk indexcluster.
intermittently specific fields, for example cf_app_name, are missing in splunk. Other fields like cf_app_id are filled correctly.

We are using splunk-nozzle tile 1.0.2 version in pivotal cloud foundry.

Please let me know if any more information is required to fix the issue .

**Comment by luckyj5** [comment] 2019-04-25 19:17
Hi, Thanks for reaching out. Can we please have below information for better understanding? 
- Recent logs from nozzle 
- Nozzle configuration? 
- Number of apps/ org/ spaces in your PCF env and data volume? 
- How frequently new applications are getting added/ or existing applications getting updated in PCF env? 

"cf_app_name" field is a part of the metadata which gets populated if "add_app_info" field is set to true in the nozzle config. 
If applications are getting updated or new applications are getting added to your PCF foundations, splunk nozzle needs to update its cache to collect updated metadata information. 2 ways to update the nozzle cache are: 
- Restart the nozzle which will trigger the cache update or
- Set "MISSING_APP_CACHE_INVALIDATE_TTL" and "APP_CACHE_INVALIDATE_TTL" to eg "300s", and nozzle will update its cache every 300s. 

Also, may I know who is the customer? and if there is a ticket open for this issue with Splunk support?
Please let me know if any question. 
Thanks!

**Comment by sabarivijayan-fd** [comment] 2019-04-26 12:13
Hi,
     Please find below comments

Recent Logs from the Nozzle
2019-04-24T12:55:11.951+05:30 [APP/PROC/WEB/5] [ERR] time="2019-04-24T07:25:11Z" level=error msg="Failed to fetch application metadata: App was missed and ignored"
2019-04-24T12:55:12.383+05:30 [APP/PROC/WEB/7] [ERR] time="2019-04-24T07:25:12Z" level=error msg="Failed to fetch application metadata: App was missed and ignored"
2019-04-24T12:55:13.006+05:30 [APP/PROC/WEB/7] [ERR] time="2019-04-24T07:25:13Z" level=error msg="Failed to fetch application metadata: App was missed and ignored"
2019-04-24T12:55:14.109+05:30 [APP/PROC/WEB/3] [ERR] time="2019-04-24T07:25:14Z" level=error msg="Failed to fetch application metadata: App was missed and ignored"

Number of apps/ org/ spaces in your PCF env and data volume
200 apps , 60 orgs and 100 spaces

How frequently new applications are getting added/ or existing applications getting updated in PCF env?
every a hour

customer : First Data
not yet created ticket with splunk support.

existing Nozzle configurations for below parameters are 0s
MISSING_APP_CACHE_INVALIDATE_TTL" and "APP_CACHE_INVALIDATE_TTL"

will change some value and check the functionality as per suggestion.

Thanks!

**Comment by luckyj5** [comment] 2019-04-26 17:38
Thanks for the update @sabarivijayan-fd. 
If you have active Splunk support entitlement, I would recommend to open a ticket through Splunk support for quicker resolutions. 

Based on the error you reported, can you please check the configured value for "IGNORE_MISSING_APP"? If it's set to true, can you please try and set it to false and see if it helps. 

Let me know if any questions. 
Thanks!

**Comment by sabarivijayan-fd** [comment] 2019-04-29 09:23
thanks for the update @luckyj5 

just need below information from you
if IGNORE_MISSING_APP is set to false , then do we need to configure MISSING_APP_CACHE_INVALIDATE_TTL" and "APP_CACHE_INVALIDATE_TTL"

if we need to configure MISSING_APP_CACHE_INVALIDATE_TTL and APP_CACHE_INVALIDATE_TTL values, what would be best threshold value for it?

Thanks

**Comment by luckyj5** [comment] 2019-04-29 17:57
@sabarivijayan-fd Yes, "MISSING_APP_CACHE_INVALIDATE_TTL" and "APP_CACHE_INVALIDATE_TTL" needs to be configured. Threshold for these params depends on how frequently new apps are getting added or existing apps are getting updated in your env. So for your env, if apps update frequency is 1 hour, then you can configure these settings to 1800s and nozzle will update cache every half an hour. 
Let me know if any questions. 
Thanks!

**Comment by luckyj5** [comment] 2019-05-13 18:29
@sabarivijayan-fd, Did the above config change help? Please let us know if any questions. Thanks!

**Comment by sabarivijayan-fd** [comment] 2019-05-16 11:23
@luckyj5 ,
                 sorry for delyaed response as i was on vacation.
                 I have changed 3 region and still getting error from only one region.

**Comment by luckyj5** [comment] 2019-05-16 17:29
@sabarivijayan-fd Thanks for the update. Did updating the config helped in resolving the issue in 2 regions? Can you share the recent nozzle logs and also if any setup/ deployment is different between 3 regions, please let me know. Thanks!

**Comment by sabarivijayan-fd** [comment] 2019-05-17 13:39
@luckyj5 , configuration of all 3 regions  are same . it is working fine in 2 regions but it is not working in one region , part of recent log for that regions is as below
2019-05-17T18:51:56.274+05:30 [APP/PROC/WEB/0] [ERR] time="2019-05-17T13:21:56Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"
2019-05-17T18:52:01.221+05:30 [APP/PROC/WEB/5] [ERR] time="2019-05-17T13:22:01Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"
2019-05-17T18:52:07.773+05:30 [APP/PROC/WEB/4] [ERR] time="2019-05-17T13:22:07Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"
2019-05-17T18:52:15.945+05:30 [APP/PROC/WEB/7] [ERR] time="2019-05-17T13:22:15Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"
2019-05-17T18:52:26.435+05:30 [APP/PROC/WEB/6] [ERR] time="2019-05-17T13:22:26Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"
2019-05-17T18:52:32.011+05:30 [APP/PROC/WEB/8] [ERR] time="2019-05-17T13:22:32Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"
2019-05-17T18:52:36.564+05:30 [APP/PROC/WEB/5] [ERR] time="2019-05-17T13:22:36Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"

**Comment by luckyj5** [comment] 2019-05-17 19:41
@sabarivijayan-fd, Thanks for the update. Does this error occur all the time and nozzle crashes coz of this? or it's happening only over some intervals and gets auto resolve and then reoccur?
 
From the error message it looks like the nozzle is trying to fetch metadata for an app which doesn't exist/ or has been deleted/ or app has been updated from its previous state. This behavior is expected if the application is missing, to avoid this you can set  `IGNORE_MISSING_APP` to true (if app is missed, it will be ignored). 



Also, please let me know the values for the following config param: 
MISSING_APP_CACHE_INVALIDATE_TTL" 
"APP_CACHE_INVALIDATE_TTL"
"IGNORE_MISSING_APP" 
"APP_LIMITS"

**Comment by sabarivijayan-fd** [comment] 2019-05-20 11:43
@luckyj5 , Thanks for the update . Please find below values for above param
MISSING_APP_CACHE_INVALIDATE_TTL - 2700s
APP_CACHE_INVALIDATE_TTL - 2700s
IGNORE_MISSING_APP - false
APP_LIMITS - 0

**Comment by sabarivijayan-fd** [comment] 2019-05-30 12:12
@luckyj5 ,  We started receiving same missing filed error from all regions now. can you please suggest what can be done to fix this issue permanently.

**Comment by luckyj5** [comment] 2019-05-30 17:25
@sabarivijayan-fd  Pardon the delay, as I said earlier, the error will occur when nozzle is trying to fetch metadata for an app which doesn't exist/ or has been deleted/ or app has been updated from its previous state. This behavior is expected if the application is missing, to avoid this you can set IGNORE_MISSING_APP to true (if app is missed, it will be ignored).

Also, does this error occur all the time and nozzle crashes coz of this? or it's happening only over some intervals and gets auto resolve and then reoccur? 
Based on the `INVALIDATE_TTL` value (i.e, 2700s), is there any change in behavior/ logs when this interval hits? 
Please let me know if any questions. 
Thanks!

**Comment by sabarivijayan-fd** [comment] 2019-05-31 12:53
@luckyj5 ,  i restarted splunk nozzle app for one region as we are getting more alerts.
existing configuration for  IGNORE_MISSING_APP is false now,
we are getting logs 
2019-05-31T18:16:02.843+05:30 [APP/PROC/WEB/0] [ERR] time="2019-05-31T12:46:02Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"
2019-05-31T18:16:33.014+05:30 [APP/PROC/WEB/0] [ERR] time="2019-05-31T12:46:33Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"
2019-05-31T18:17:02.874+05:30 [APP/PROC/WEB/1] [ERR] time="2019-05-31T12:47:02Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"
2019-05-31T18:17:32.898+05:30 [APP/PROC/WEB/0] [ERR] time="2019-05-31T12:47:32Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"
2019-05-31T18:18:02.821+05:30 [APP/PROC/WEB/1] [ERR] time="2019-05-31T12:48:02Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"
2019-05-31T18:18:24.534+05:30 [APP/PROC/WEB/1] [ERR] time="2019-05-31T12:48:24Z" level=error msg="Failed to fetch application metadata: Error requesting apps: cfclient: error (100004): CF-AppNotFound"

do we lose any app log if we set IGNORE_MISSING_APP  to true?

**Comment by luckyj5** [comment] 2019-06-17 18:04
@sabarivijayan-fd Pardon the delay, `AppNotFound` error is related to when nozzle is unable to locate an existing app. Will need to investigate further to get to the root cause in this case. If possible, please open a support case with Splunk for quicker resolutions. 
Also, release v1.1.1 will be out soon which will include an upgrade to `cfclient` which could help with the issue since the errors are also related to `cfclient`. 
Thanks!

**Comment by luckyj5** [comment] 2019-08-09 03:33
If the issue still exist, please try the new release (https://github.com/cloudfoundry-community/splunk-firehose-nozzle/releases/tag/1.1.2) which now uses UAA Client ID and Client secret instead of API User and API Password for authentication and refresh token mechanism. 
Please re-open is issue still exist. Thanks!

**Closed by luckyj5** 2019-08-09 03:33 UTC
